#include <iostream>
#include <fstream>
#include <string>
#include <stack>
#include <vector>
#include <map>

using namespace std;

// TODO: Read bytecode file, execute instructions using a stack machine
// WHY: The assignment requires a separate program that can run the generated bytecode.
//      A stack machine is the simplest possible execution model — every operand is
//      pushed onto a value stack, every operator pops its inputs and pushes its result,
//      and STORE/LOAD move values to/from a variable map. No register allocation or
//      complex memory model is needed, which keeps the implementation minimal.

int main(int argc, char** argv) {
    if (argc < 2) {
        cerr << "Usage: interpreter <bytecode_file>" << endl;
        return 1;
    }

    ifstream file(argv[1]);
    if (!file.is_open()) {
        cerr << "Error: cannot open file '" << argv[1] << "'" << endl;
        return 1;
    }

    vector<string> instructions;
    string line;
    while (getline(file, line)) {
        if (!line.empty())
            instructions.push_back(line);
    }
    file.close();

    // TODO: For each line, parse the opcode and operands
    // WHY: Text-based bytecode (one instruction per line) lets us use simple string
    //      splitting — no custom binary parser needed.

    // TODO: Dispatch on opcode and execute using a std::stack<double> value stack
    //        and a std::map<string,double> variable store
    // WHY: The stack holds intermediate results for expression evaluation.
    //      The variable map holds named locals (e.g. "result") across instructions.

    // TODO: Handle HALT to stop execution cleanly
    // WHY: The bytecode file ends with a HALT instruction; without it the interpreter
    //      would fall off the end of the instruction list and invoke undefined behaviour.

    return 0;
}
